import type { Metadata } from "next";
import {  Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Breadcrumbs from "@/components/ui/BreadCrumbs";
import ScrollToTop from "@/components/layout/ScrollToTop";


const lato = Nunito({
  // variable: "--font-lato",
  subsets: ["latin"],
  weight:[ "300","400","700","900"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased`}
      >
        <Navbar/>
        <Breadcrumbs/>
        <ScrollToTop/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
